version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deployment
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/start_server
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 60
      runas: root
